USE LogisticaSur;

# 5 KG
insert into zona_precio (zona,precio,kilos) values ("caba","450","5");
insert into zona_precio (zona,precio,kilos) values ("quilmes","300","5");
insert into zona_precio (zona,precio,kilos) values ("bernal","300","5");
insert into zona_precio (zona,precio,kilos) values ("berazategui","300","5");
insert into zona_precio (zona,precio,kilos) values ("ranelagh","500","5");
insert into zona_precio (zona,precio,kilos) values ("bosques","500","5");
insert into zona_precio (zona,precio,kilos) values ("solano","500","5");
insert into zona_precio (zona,precio,kilos) values ("varela","500","5");
insert into zona_precio (zona,precio,kilos) values ("sarandi","500","5");
insert into zona_precio (zona,precio,kilos) values ("la plata","600","5");
insert into zona_precio (zona,precio,kilos) values ("ezeiza","600","5");
insert into zona_precio (zona,precio,kilos) values ("la matanza","600","5");
insert into zona_precio (zona,precio,kilos) values ("moron","600","5");
insert into zona_precio (zona,precio,kilos) values ("hurlingham","600","5");
insert into zona_precio (zona,precio,kilos) values ("ciudadela","600","5");
insert into zona_precio (zona,precio,kilos) values ("caceros","600","5");
insert into zona_precio (zona,precio,kilos) values ("san martin","600","5");
insert into zona_precio (zona,precio,kilos) values ("martinez","600","5");
insert into zona_precio (zona,precio,kilos) values ("olivos","600","5");
insert into zona_precio (zona,precio,kilos) values ("san isidro","600","5");
insert into zona_precio (zona,precio,kilos) values ("boulogne","600","5");
insert into zona_precio (zona,precio,kilos) values ("villa ballester","600","5");
insert into zona_precio (zona,precio,kilos) values ("san vicente","650","5");
insert into zona_precio (zona,precio,kilos) values ("a. korn","650","5");
insert into zona_precio (zona,precio,kilos) values ("j.c. paz","650","5");
insert into zona_precio (zona,precio,kilos) values ("san miguel","650","5");
insert into zona_precio (zona,precio,kilos) values ("tigre","650","5");
insert into zona_precio (zona,precio,kilos) values ("don torcuato","650","5");
insert into zona_precio (zona,precio,kilos) values ("pacheco","650","5");
insert into zona_precio (zona,precio,kilos) values ("los polvorines","650","5");
insert into zona_precio (zona,precio,kilos) values ("tortugitas","650","5");
insert into zona_precio (zona,precio,kilos) values ("del viso","650","5");
insert into zona_precio (zona,precio,kilos) values ("calzada","400","5");
insert into zona_precio (zona,precio,kilos) values ("temperley","400","5");
insert into zona_precio (zona,precio,kilos) values ("banfield","400","5");
insert into zona_precio (zona,precio,kilos) values ("lanus","400","5");
insert into zona_precio (zona,precio,kilos) values ("avellaneda","400","5");
insert into zona_precio (zona,precio,kilos) values ("lomas de zamora","400","5");
insert into zona_precio (zona,precio,kilos) values ("burzaco","400","5");
insert into zona_precio (zona,precio,kilos) values ("monte grande","400","5");
insert into zona_precio (zona,precio,kilos) values ("cañuelas","800","5");
insert into zona_precio (zona,precio,kilos) values ("marcos paz","800","5");
insert into zona_precio (zona,precio,kilos) values ("general rodriguez","800","5");
insert into zona_precio (zona,precio,kilos) values ("ituzaingo","650","5");
insert into zona_precio (zona,precio,kilos) values ("merlo","650","5");
insert into zona_precio (zona,precio,kilos) values ("moreno","650","5");
insert into zona_precio (zona,precio,kilos) values ("pilar","650","5");
insert into zona_precio (zona,precio,kilos) values ("garin","650","5");
insert into zona_precio (zona,precio,kilos) values ("escobar","650","5");
insert into zona_precio (zona,precio,kilos) values ("campana","1000","5");
insert into zona_precio (zona,precio,kilos) values ("zarate","1000","5");
insert into zona_precio (zona,precio,kilos) values ("lujan","1000","5");

#10 KG
insert into zona_precio (zona,precio,kilos) values ("caba","500","10");
insert into zona_precio (zona,precio,kilos) values ("quilmes","350","10");
insert into zona_precio (zona,precio,kilos) values ("bernal","350","10");
insert into zona_precio (zona,precio,kilos) values ("berazategui","350","10");
insert into zona_precio (zona,precio,kilos) values ("ranelagh","600","10");
insert into zona_precio (zona,precio,kilos) values ("bosques","600","10");
insert into zona_precio (zona,precio,kilos) values ("solano","600","10");
insert into zona_precio (zona,precio,kilos) values ("varela","600","10");
insert into zona_precio (zona,precio,kilos) values ("sarandi","600","10");
insert into zona_precio (zona,precio,kilos) values ("la plata","750","10");
insert into zona_precio (zona,precio,kilos) values ("ezeiza","750","10");
insert into zona_precio (zona,precio,kilos) values ("la matanza","750","10");
insert into zona_precio (zona,precio,kilos) values ("moron","750","10");
insert into zona_precio (zona,precio,kilos) values ("hurlingham","750","10");
insert into zona_precio (zona,precio,kilos) values ("ciudadela","750","10");
insert into zona_precio (zona,precio,kilos) values ("caceros","750","10");
insert into zona_precio (zona,precio,kilos) values ("san martin","750","10");
insert into zona_precio (zona,precio,kilos) values ("martinez","750","10");
insert into zona_precio (zona,precio,kilos) values ("olivos","750","10");
insert into zona_precio (zona,precio,kilos) values ("san isidro","750","10");
insert into zona_precio (zona,precio,kilos) values ("boulogne","750","10");
insert into zona_precio (zona,precio,kilos) values ("villa ballester","750","10");
insert into zona_precio (zona,precio,kilos) values ("san vicente","800","10");
insert into zona_precio (zona,precio,kilos) values ("a. korn","800","10");
insert into zona_precio (zona,precio,kilos) values ("j.c. paz","800","10");
insert into zona_precio (zona,precio,kilos) values ("san miguel","800","10");
insert into zona_precio (zona,precio,kilos) values ("tigre","800","10");
insert into zona_precio (zona,precio,kilos) values ("don torcuato","800","10");
insert into zona_precio (zona,precio,kilos) values ("pacheco","800","10");
insert into zona_precio (zona,precio,kilos) values ("los polvorines","800","10");
insert into zona_precio (zona,precio,kilos) values ("tortugitas","800","10");
insert into zona_precio (zona,precio,kilos) values ("del viso","800","10");
insert into zona_precio (zona,precio,kilos) values ("calzada","500","10");
insert into zona_precio (zona,precio,kilos) values ("temperley","500","10");
insert into zona_precio (zona,precio,kilos) values ("banfield","500","10");
insert into zona_precio (zona,precio,kilos) values ("lanus","500","10");
insert into zona_precio (zona,precio,kilos) values ("avellaneda","500","10");
insert into zona_precio (zona,precio,kilos) values ("lomas de zamora","500","10");
insert into zona_precio (zona,precio,kilos) values ("burzaco","500","10");
insert into zona_precio (zona,precio,kilos) values ("monte grande","500","10");
insert into zona_precio (zona,precio,kilos) values ("cañuelas","1100","10");
insert into zona_precio (zona,precio,kilos) values ("marcos paz","1100","10");
insert into zona_precio (zona,precio,kilos) values ("general rodriguez","1100","10");
insert into zona_precio (zona,precio,kilos) values ("ituzaingo","850","10");
insert into zona_precio (zona,precio,kilos) values ("merlo","850","10");
insert into zona_precio (zona,precio,kilos) values ("moreno","850","10");
insert into zona_precio (zona,precio,kilos) values ("pilar","850","10");
insert into zona_precio (zona,precio,kilos) values ("garin","850","10");
insert into zona_precio (zona,precio,kilos) values ("escobar","850","10");
insert into zona_precio (zona,precio,kilos) values ("campana","1300","10");
insert into zona_precio (zona,precio,kilos) values ("zarate","1300","10");
insert into zona_precio (zona,precio,kilos) values ("lujan","1300","10");

# 20 KG
insert into zona_precio (zona,precio,kilos) values ("caba","550","20");
insert into zona_precio (zona,precio,kilos) values ("quilmes","500","20");
insert into zona_precio (zona,precio,kilos) values ("bernal","500","20");
insert into zona_precio (zona,precio,kilos) values ("berazategui","500","20");
insert into zona_precio (zona,precio,kilos) values ("ranelagh","750","20");
insert into zona_precio (zona,precio,kilos) values ("bosques","750","20");
insert into zona_precio (zona,precio,kilos) values ("solano","750","20");
insert into zona_precio (zona,precio,kilos) values ("varela","750","20");
insert into zona_precio (zona,precio,kilos) values ("sarandi","750","20");
insert into zona_precio (zona,precio,kilos) values ("la plata","900","20");
insert into zona_precio (zona,precio,kilos) values ("ezeiza","900","20");
insert into zona_precio (zona,precio,kilos) values ("la matanza","900","20");
insert into zona_precio (zona,precio,kilos) values ("moron","900","20");
insert into zona_precio (zona,precio,kilos) values ("hurlingham","900","20");
insert into zona_precio (zona,precio,kilos) values ("ciudadela","900","20");
insert into zona_precio (zona,precio,kilos) values ("caceros","900","20");
insert into zona_precio (zona,precio,kilos) values ("san martin","900","20");
insert into zona_precio (zona,precio,kilos) values ("martinez","900","20");
insert into zona_precio (zona,precio,kilos) values ("olivos","900","20");
insert into zona_precio (zona,precio,kilos) values ("san isidro","900","20");
insert into zona_precio (zona,precio,kilos) values ("boulogne","900","20");
insert into zona_precio (zona,precio,kilos) values ("villa ballester","900","20");
insert into zona_precio (zona,precio,kilos) values ("san vicente","1000","20");
insert into zona_precio (zona,precio,kilos) values ("a. korn","1000","20");
insert into zona_precio (zona,precio,kilos) values ("j.c. paz","1000","20");
insert into zona_precio (zona,precio,kilos) values ("san miguel","1000","20");
insert into zona_precio (zona,precio,kilos) values ("tigre","1000","20");
insert into zona_precio (zona,precio,kilos) values ("don torcuato","1000","20");
insert into zona_precio (zona,precio,kilos) values ("pacheco","1000","20");
insert into zona_precio (zona,precio,kilos) values ("los polvorines","1000","20");
insert into zona_precio (zona,precio,kilos) values ("tortugitas","1000","20");
insert into zona_precio (zona,precio,kilos) values ("del viso","1000","20");
insert into zona_precio (zona,precio,kilos) values ("calzada","650","20");
insert into zona_precio (zona,precio,kilos) values ("temperley","650","20");
insert into zona_precio (zona,precio,kilos) values ("banfield","650","20");
insert into zona_precio (zona,precio,kilos) values ("lanus","650","20");
insert into zona_precio (zona,precio,kilos) values ("avellaneda","650","20");
insert into zona_precio (zona,precio,kilos) values ("lomas de zamora","650","20");
insert into zona_precio (zona,precio,kilos) values ("burzaco","650","20");
insert into zona_precio (zona,precio,kilos) values ("monte grande","650","20");
insert into zona_precio (zona,precio,kilos) values ("cañuelas","1300","20");
insert into zona_precio (zona,precio,kilos) values ("marcos paz","1300","20");
insert into zona_precio (zona,precio,kilos) values ("general rodriguez","1300","20");
insert into zona_precio (zona,precio,kilos) values ("ituzaingo","1050","20");
insert into zona_precio (zona,precio,kilos) values ("merlo","1050","20");
insert into zona_precio (zona,precio,kilos) values ("moreno","1050","20");
insert into zona_precio (zona,precio,kilos) values ("pilar","1050","20");
insert into zona_precio (zona,precio,kilos) values ("garin","1050","20");
insert into zona_precio (zona,precio,kilos) values ("escobar","1050","20");
insert into zona_precio (zona,precio,kilos) values ("campana","1500","20");
insert into zona_precio (zona,precio,kilos) values ("zarate","1500","20");
insert into zona_precio (zona,precio,kilos) values ("lujan","1500","20");

# 50 KG
insert into zona_precio (zona,precio,kilos) values ("caba","850","50");
insert into zona_precio (zona,precio,kilos) values ("quilmes","800","50");
insert into zona_precio (zona,precio,kilos) values ("bernal","800","50");
insert into zona_precio (zona,precio,kilos) values ("berazategui","800","50");
insert into zona_precio (zona,precio,kilos) values ("ranelagh","1050","50");
insert into zona_precio (zona,precio,kilos) values ("bosques","1050","50");
insert into zona_precio (zona,precio,kilos) values ("solano","1050","50");
insert into zona_precio (zona,precio,kilos) values ("varela","1050","50");
insert into zona_precio (zona,precio,kilos) values ("sarandi","1050","50");
insert into zona_precio (zona,precio,kilos) values ("la plata","1200","50");
insert into zona_precio (zona,precio,kilos) values ("ezeiza","1200","50");
insert into zona_precio (zona,precio,kilos) values ("la matanza","1200","50");
insert into zona_precio (zona,precio,kilos) values ("moron","1200","50");
insert into zona_precio (zona,precio,kilos) values ("hurlingham","1200","50");
insert into zona_precio (zona,precio,kilos) values ("ciudadela","1200","50");
insert into zona_precio (zona,precio,kilos) values ("caceros","1200","50");
insert into zona_precio (zona,precio,kilos) values ("san martin","1200","50");
insert into zona_precio (zona,precio,kilos) values ("martinez","1200","50");
insert into zona_precio (zona,precio,kilos) values ("olivos","1200","50");
insert into zona_precio (zona,precio,kilos) values ("san isidro","1200","50");
insert into zona_precio (zona,precio,kilos) values ("boulogne","1200","50");
insert into zona_precio (zona,precio,kilos) values ("villa ballester","1200","50");
insert into zona_precio (zona,precio,kilos) values ("san vicente","1400","50");
insert into zona_precio (zona,precio,kilos) values ("a. korn","1400","50");
insert into zona_precio (zona,precio,kilos) values ("j.c. paz","1400","50");
insert into zona_precio (zona,precio,kilos) values ("san miguel","1400","50");
insert into zona_precio (zona,precio,kilos) values ("tigre","1400","50");
insert into zona_precio (zona,precio,kilos) values ("don torcuato","1400","50");
insert into zona_precio (zona,precio,kilos) values ("pacheco","1400","50");
insert into zona_precio (zona,precio,kilos) values ("los polvorines","1400","50");
insert into zona_precio (zona,precio,kilos) values ("tortugitas","1400","50");
insert into zona_precio (zona,precio,kilos) values ("del viso","1400","50");
insert into zona_precio (zona,precio,kilos) values ("calzada","950","50");
insert into zona_precio (zona,precio,kilos) values ("temperley","950","50");
insert into zona_precio (zona,precio,kilos) values ("banfield","950","50");
insert into zona_precio (zona,precio,kilos) values ("lanus","950","50");
insert into zona_precio (zona,precio,kilos) values ("avellaneda","950","50");
insert into zona_precio (zona,precio,kilos) values ("lomas de zamora","950","50");
insert into zona_precio (zona,precio,kilos) values ("burzaco","950","50");
insert into zona_precio (zona,precio,kilos) values ("monte grande","950","50");
insert into zona_precio (zona,precio,kilos) values ("cañuelas","1800","50");
insert into zona_precio (zona,precio,kilos) values ("marcos paz","1800","50");
insert into zona_precio (zona,precio,kilos) values ("general rodriguez","1800","50");
insert into zona_precio (zona,precio,kilos) values ("ituzaingo","1600","50");
insert into zona_precio (zona,precio,kilos) values ("merlo","1600","50");
insert into zona_precio (zona,precio,kilos) values ("moreno","1600","50");
insert into zona_precio (zona,precio,kilos) values ("pilar","1600","50");
insert into zona_precio (zona,precio,kilos) values ("garin","1600","50");
insert into zona_precio (zona,precio,kilos) values ("escobar","1600","50");
insert into zona_precio (zona,precio,kilos) values ("campana","2000","50");
insert into zona_precio (zona,precio,kilos) values ("zarate","2000","50");
insert into zona_precio (zona,precio,kilos) values ("lujan","2000","50");
